import { db } from '@/lib/firebase';
import { collection, query, where, getDocs, onSnapshot, Unsubscribe } from 'firebase/firestore';
import { useGymStore } from '@/store';

export interface NormalizedBillingTransaction {
  id: string;
  invoiceNumber: string;
  invoice: string;
  memberId: string;
  clientId?: string;
  memberName: string;
  memberPhone?: string;
  billingType: 'membership' | 'pt' | 'other';
  transactionType?: string;
  plan: string;
  packageName: string;
  date: string;
  billDate: string;
  startDate: string;
  expiryDate: string;
  amount: number;
  originalAmount: number;
  discount: number;
  discountAmount: number;
  tax: number;
  taxAmount: number;
  otherCharges: number;
  netPayable: number;
  paid: number;
  amountPaid: number;
  pendingAmount: number;
  balanceAmount: number;
  method: string;
  paymentMethod: string;
  status: 'paid' | 'partial' | 'pending' | 'void';
  isHistorical?: boolean;
  isAutoGenerated?: boolean;
  createdAt: string;
  raw: any;
}

export interface BillingSummary {
  totalBilled: number;
  totalCollected: number;
  totalPending: number;
}

export interface BillingDiagnostics {
  memberDocId: string;
  canonicalMemberId: string;
  allMemberKeys: string[];
  phoneMatched: string;
  nameMatched: string;
  firestoreLiveCount: number;
  embeddedCount: number;
  normalizedCount: number;
  billed: number;
  collected: number;
  pending: number;
}

export interface UpgradeBillParams {
  previousPackageAmount: number;
  previousAmountPaid: number;
  previousOutstanding: number;
  newPackageAmount: number;
  discount: number;
  amountPaidTodayInput?: number;
}

export interface UpgradeBillResult {
  previousPackageAmount: number;
  previousAmountPaid: number;
  previousOutstanding: number;
  newPackageAmount: number;
  carryForwardCredit: number;
  upgradeAmountBeforeDiscount: number;
  discount: number;
  finalPayable: number;
  amountPaidToday: number;
  remainingPending: number;
}

/**
 * Robust price extraction helper from plan strings (e.g. "3 months ₹6,500" -> 6500)
 * Prevents matching month count (3 or 6) as price.
 */
export function extractPriceFromPlanString(planStr?: string): number {
  if (!planStr || typeof planStr !== 'string') return 0;

  // 1. Match explicit currency symbol ₹ or Rs. followed by numbers (e.g., "3 months ₹6,500" or "Rs 12000")
  const currencyMatch = planStr.match(/(?:₹|rs\.?)\s*([0-9,]+)/i);
  if (currencyMatch && currencyMatch[1]) {
    const val = Number(currencyMatch[1].replace(/,/g, ''));
    if (!isNaN(val) && val > 0) return val;
  }

  // 2. Match standalone numbers >= 100 in the string (e.g. "3 Months 6500" or "12 Months 15000")
  const numberMatches = planStr.match(/\b([0-9]{3,6})\b/g);
  if (numberMatches && numberMatches.length > 0) {
    const val = Number(numberMatches[0].replace(/,/g, ''));
    if (!isNaN(val) && val >= 100) return val;
  }

  return 0;
}

/**
 * Default standard plan price resolution based on duration or keywords.
 * Resolves "1 Month" / "Monthly" / "1M" to 2000 (instead of 6500 fallback).
 */
export function getDefaultPriceForPlan(planStr?: string): number {
  if (!planStr || typeof planStr !== 'string') return 2000;

  const extracted = extractPriceFromPlanString(planStr);
  if (extracted > 0) return extracted;

  const lower = planStr.toLowerCase().trim();
  if (lower.includes('1 month') || lower.includes('monthly') || lower.includes('1m') || lower.includes('standard')) {
    return 2000;
  }
  if (lower.includes('2 month') || lower.includes('2m')) {
    return 4000;
  }
  if (lower.includes('3 month') || lower.includes('quarterly') || lower.includes('3m') || lower.includes('pro') || lower.includes('prime')) {
    return 6500;
  }
  if (lower.includes('6 month') || lower.includes('semi') || lower.includes('6m')) {
    return 10000;
  }
  if (lower.includes('12 month') || lower.includes('1 year') || lower.includes('annual') || lower.includes('12m')) {
    return 18000;
  }

  return 2000;
}

/**
 * CENTRAL UPGRADE CALCULATION ENGINE (Rule & Hard Correction)
 * Upgrades adjust previous paid money against new package price:
 * Upgrade Amount = New Package - Carry Forward Credit (Previous Paid)
 * Final Payable = max(0, Upgrade Amount - Discount)
 */
export function calculateUpgradeBill(params: UpgradeBillParams): UpgradeBillResult {
  const previousPackageAmount = Math.max(0, Number(params.previousPackageAmount) || 0);
  const previousAmountPaid = Math.max(0, Number(params.previousAmountPaid) || 0);
  const previousOutstanding = Math.max(0, Number(params.previousOutstanding) || 0);
  const newPackageAmount = Math.max(0, Number(params.newPackageAmount) || 0);
  const discount = Math.max(0, Number(params.discount) || 0);

  // Carry Forward Credit = Previous Amount Paid used as adjustment
  const carryForwardCredit = previousAmountPaid;

  // Upgrade Amount Before Discount = New Package Amount - Carry Forward Credit
  const upgradeAmountBeforeDiscount = Math.max(0, newPackageAmount - carryForwardCredit);

  // Final Payable = max(0, Upgrade Amount Before Discount - Discount)
  const finalPayable = Math.max(0, upgradeAmountBeforeDiscount - discount);

  // Amount Paid Today
  const amountPaidToday = params.amountPaidTodayInput !== undefined
    ? Math.min(finalPayable, Math.max(0, Number(params.amountPaidTodayInput) || 0))
    : finalPayable;

  // Remaining Pending
  const remainingPending = Math.max(0, finalPayable - amountPaidToday);

  return {
    previousPackageAmount,
    previousAmountPaid,
    previousOutstanding,
    newPackageAmount,
    carryForwardCredit,
    upgradeAmountBeforeDiscount,
    discount,
    finalPayable,
    amountPaidToday,
    remainingPending
  };
}

/**
 * 1. RESOLVE ALL STABLE MEMBER IDENTIFIER KEYS
 * Given any member object or string, extracts all variations:
 * - docId / id / uid
 * - memberId (e.g. AZ-2026-0028)
 * - clientId (e.g. 28)
 * - member_28, member_AZ-2026-0028
 * - numeric suffix (28)
 * - phone number
 * - member name
 */
export function resolveMemberIdentifierKeys(member: any): { keysSet: Set<string>; cleanNumsSet: Set<string>; phone: string; name: string } {
  if (!member) return { keysSet: new Set(), cleanNumsSet: new Set(), phone: '', name: '' };

  const storeMembers = typeof window !== 'undefined' ? (useGymStore.getState?.()?.members || []) : [];
  
  // Find matching member record in store if available to merge all possible identifiers
  let fullMember = typeof member === 'object' ? member : null;
  if (storeMembers.length > 0) {
    const searchTarget = (typeof member === 'string' ? member : (member?.id || member?.memberId || member?.phone || member?.name || '')).trim().toLowerCase();
    const storeMatch = storeMembers.find((sm: any) => {
      if (!sm) return false;
      const smId = String(sm.id || '').toLowerCase();
      const smDocId = String(sm.docId || '').toLowerCase();
      const smMemberId = String(sm.memberId || '').toLowerCase();
      const smClientId = String(sm.clientId || '').toLowerCase();
      const smPhone = String(sm.phone || '').replace(/\D/g, '');
      const smName = String(sm.name || '').trim().toLowerCase();
      return (
        smId === searchTarget ||
        smDocId === searchTarget ||
        smMemberId === searchTarget ||
        smClientId === searchTarget ||
        (smPhone && searchTarget.replace(/\D/g, '') && smPhone.endsWith(searchTarget.replace(/\D/g, ''))) ||
        (smName && smName === searchTarget)
      );
    });
    if (storeMatch) {
      fullMember = { ...storeMatch, ...fullMember };
    }
  }

  const m = fullMember || (typeof member === 'object' ? member : {});
  const rawKeys: string[] = [];

  if (typeof member === 'string') rawKeys.push(member);
  if (m.id) rawKeys.push(String(m.id));
  if (m.docId) rawKeys.push(String(m.docId));
  if (m.uid) rawKeys.push(String(m.uid));
  if (m.memberId) rawKeys.push(String(m.memberId));
  if (m.clientId) rawKeys.push(String(m.clientId));
  if (m.memberCode) rawKeys.push(String(m.memberCode));
  if (m.employeeId) rawKeys.push(String(m.employeeId));

  if (m.clientId) {
    rawKeys.push(`member_${m.clientId}`);
    rawKeys.push(`member_AZ-${m.clientId}`);
    rawKeys.push(`member_AZ-2026-${m.clientId}`);
  }
  if (m.memberId) {
    rawKeys.push(`member_${m.memberId}`);
  }

  const keysSet = new Set<string>();
  const cleanNumsSet = new Set<string>();

  rawKeys.forEach(k => {
    if (!k) return;
    const lower = k.trim().toLowerCase();
    keysSet.add(lower);

    // Extract numeric portion (e.g. "AZ-2026-0028" -> "28" or "0028")
    const cleanNum = lower.replace(/^(member_|az-2026-|az-)/i, '').replace(/^0+/, '');
    if (cleanNum) cleanNumsSet.add(cleanNum);
  });

  const rawPhone = m.phone || m.mobile || m.memberPhone || '';
  const phone = String(rawPhone).replace(/\D/g, '');

  const rawName = m.name || m.memberName || '';
  const name = String(rawName).trim().toLowerCase();

  return { keysSet, cleanNumsSet, phone, name };
}

/**
 * 2. MATCH AN INVOICE RECORD AGAINST MEMBER IDENTIFIERS
 */
export function isInvoiceMatchingMember(inv: any, memberInfo: { keysSet: Set<string>; cleanNumsSet: Set<string>; phone: string; name: string }): boolean {
  if (!inv || inv.deleted === true || String(inv.status || '').toLowerCase() === 'void' || inv.isDuplicate === true) {
    return false;
  }

  const { keysSet, cleanNumsSet, phone, name } = memberInfo;

  const invKeys = [
    inv.memberId,
    inv.clientId,
    inv.uid,
    inv.docId,
    inv.memberCode,
    inv.employeeId,
    inv.userId,
    inv.id
  ].filter(Boolean).map(x => String(x).trim().toLowerCase());

  // Direct match on any key
  for (const ik of invKeys) {
    if (keysSet.has(ik)) return true;

    const invCleanNum = ik.replace(/^(member_|az-2026-|az-)/i, '').replace(/^0+/, '');
    if (invCleanNum && cleanNumsSet.has(invCleanNum)) return true;
  }

  // Phone match as secondary fallback
  if (phone && phone.length >= 7) {
    const invPhone = String(inv.memberPhone || inv.phone || inv.mobile || '').replace(/\D/g, '');
    if (invPhone && (invPhone === phone || invPhone.endsWith(phone) || phone.endsWith(invPhone))) {
      return true;
    }
  }

  // Name match fallback if member name matches exactly
  if (name && name.length >= 3) {
    const invName = String(inv.memberName || inv.name || '').trim().toLowerCase();
    if (invName && invName === name) {
      return true;
    }
  }

  return false;
}

/**
 * 3. NORMALIZE A RAW BILLING TRANSACTION RECORD
 */
export function normalizeBillingTransaction(rawRecord: any, defaultMember?: any): NormalizedBillingTransaction {
  const r = rawRecord || {};

  let origAmt = Number(r.originalAmount !== undefined ? r.originalAmount : (r.packagePrice || r.price || r.amount || r.totalBilled || 0));
  
  // If original price is missing/0, attempt extraction or default price resolution from plan/packageName
  if (origAmt === 0) {
    origAmt = getDefaultPriceForPlan(r.plan || r.packageName || defaultMember?.plan || defaultMember?.packageName);
  }

  const discAmt = Number(r.discountAmount !== undefined ? r.discountAmount : (r.discount || 0));
  const taxAmt = Number(r.taxAmount !== undefined ? r.taxAmount : (r.tax || r.gst || 0));
  const othAmt = Number(r.otherCharges || 0);

  const calcNet = Math.max(0, origAmt - discAmt + taxAmt + othAmt);
  let netPayable = Number(r.netPayable !== undefined ? r.netPayable : (r.amount !== undefined ? r.amount : calcNet));
  if (netPayable === 0 && origAmt > 0) {
    netPayable = origAmt;
  }

  let amountPaid = Number(
    r.amountPaid !== undefined ? r.amountPaid :
    (r.paid !== undefined ? r.paid :
    (r.amountPaidToday !== undefined ? r.amountPaidToday :
    (r.paidAmount !== undefined ? r.paidAmount :
    (r.totalPaid !== undefined ? r.totalPaid : 0))))
  );

  const defaultBalance = Number(
    defaultMember?.outstandingBalance ??
    defaultMember?.balanceAmount ??
    defaultMember?.balanceDue ??
    defaultMember?.dueAmount ??
    defaultMember?.pendingAmount ?? 0
  );

  if (amountPaid === 0 && netPayable > 0) {
    const isMemberPaid = (defaultMember?.paymentStatus || '').toLowerCase() === 'paid' ||
                         (defaultMember?.status || '').toLowerCase() === 'active' ||
                         defaultBalance === 0;
    if (isMemberPaid) {
      amountPaid = Math.max(0, netPayable - defaultBalance);
      if (amountPaid === 0 && defaultBalance === 0) amountPaid = netPayable;
    } else if (defaultMember?.totalPaid && defaultMember.totalPaid > 0) {
      amountPaid = Number(defaultMember.totalPaid);
    }
  }

  const rawPending = r.pendingAmount !== undefined ? r.pendingAmount : (r.balanceAmount !== undefined ? r.balanceAmount : (r.outstandingAmount !== undefined ? r.outstandingAmount : (r.remainingBalance !== undefined ? r.remainingBalance : Math.max(0, netPayable - amountPaid))));
  const pendingAmount = Math.max(0, Number(rawPending) || 0);

  let status: 'paid' | 'partial' | 'pending' | 'void' = 'paid';
  const rawStatus = String(r.status || r.paymentStatus || '').toLowerCase();
  if (rawStatus === 'void' || r.deleted === true) {
    status = 'void';
  } else if (pendingAmount === 0 || rawStatus === 'paid') {
    status = 'paid';
  } else if (amountPaid > 0 || rawStatus === 'partial') {
    status = 'partial';
  } else {
    status = 'pending';
  }

  const invNum = r.invoiceNumber || r.invoice || r.invoiceNo || (r.clientId ? `INV-LEG-${r.clientId}` : (r.id ? `INV-${r.id}` : 'INV-001'));
  const bType = String(r.billingType || r.invoiceType || r.type || '').toLowerCase().includes('pt') ? 'pt' : 'membership';

  const planName = r.plan || r.packageName || r.package || defaultMember?.plan || defaultMember?.packageName || 'General Membership';
  const dateStr = r.billDate || r.date || r.paymentDate || r.startDate || r.createdAt || new Date().toISOString().split('T')[0];

  return {
    id: String(r.id || invNum),
    invoiceNumber: String(invNum),
    invoice: String(invNum),
    memberId: String(r.memberId || defaultMember?.id || defaultMember?.memberId || ''),
    clientId: r.clientId ? String(r.clientId) : undefined,
    memberName: String(r.memberName || defaultMember?.name || 'Gym Member'),
    memberPhone: String(r.memberPhone || r.phone || defaultMember?.phone || ''),
    billingType: bType,
    transactionType: r.transactionType || r.type || 'membership_payment',
    plan: String(planName),
    packageName: String(planName),
    date: String(dateStr),
    billDate: String(dateStr),
    startDate: String(r.startDate || dateStr),
    expiryDate: String(r.expiryDate || r.endDate || ''),
    amount: (status === 'paid' && amountPaid > 0 && amountPaid < netPayable) ? amountPaid : netPayable,
    originalAmount: origAmt,
    discount: discAmt,
    discountAmount: discAmt,
    tax: taxAmt,
    taxAmount: taxAmt,
    otherCharges: othAmt,
    netPayable,
    paid: amountPaid,
    amountPaid,
    pendingAmount,
    balanceAmount: pendingAmount,
    method: String(r.paymentMethod || r.method || 'Cash'),
    paymentMethod: String(r.paymentMethod || r.method || 'Cash'),
    status,
    isHistorical: Boolean(r.isHistorical || r.imported || r.isLegacyImport),
    isAutoGenerated: Boolean(r.isAutoGenerated),
    createdAt: String(r.createdAt || dateStr),
    raw: r
  };
}

/**
 * 4. CALCULATE CANONICAL FINANCIAL SUMMARY
 */
export function calculateBillingSummary(transactions: NormalizedBillingTransaction[]): BillingSummary {
  const active = transactions.filter(t => t.status !== 'void');

  const totalBilled = active.reduce((sum, t) => {
    const isUp = t.transactionType === 'membership_upgrade' || String(t.invoiceNumber || '').startsWith('INV-UPG');
    if (isUp) {
      return sum + t.netPayable;
    }
    return sum + (t.netPayable || t.originalAmount);
  }, 0);

  const totalCollected = active.reduce((sum, t) => sum + t.amountPaid, 0);
  const totalPending = Math.max(0, totalBilled - totalCollected);

  return { totalBilled, totalCollected, totalPending };
}

/**
 * 5. GET MEMBER BILLING TRANSACTIONS (REALTIME LISTENER WITH EMBEDDED FALLBACKS & STORE FALLBACK)
 */
export function listenMemberBillingTransactions(
  member: any,
  onUpdate: (transactions: NormalizedBillingTransaction[], summary: BillingSummary, diagnostics: BillingDiagnostics) => void
): Unsubscribe {
  if (!member) {
    onUpdate([], { totalBilled: 0, totalCollected: 0, totalPending: 0 }, {
      memberDocId: '',
      canonicalMemberId: '',
      allMemberKeys: [],
      phoneMatched: '',
      nameMatched: '',
      firestoreLiveCount: 0,
      embeddedCount: 0,
      normalizedCount: 0,
      billed: 0,
      collected: 0,
      pending: 0
    });
    return () => {};
  }

  const memberInfo = resolveMemberIdentifierKeys(member);

  // Embedded records on member document
  const embeddedRaw: any[] = [
    ...(Array.isArray(member.billingHistory) ? member.billingHistory : []),
    ...(Array.isArray(member.payments) ? member.payments : []),
    ...(Array.isArray(member.membershipHistory) ? member.membershipHistory : []),
    ...(Array.isArray(member.ptHistory) ? member.ptHistory : [])
  ];

  const buildNormalizedList = (matchedDocs: any[]) => {
    const combinedMap = new Map<string, any>();

    // 0. Store payments matching this member
    const storePayments = typeof window !== 'undefined' ? (useGymStore.getState?.()?.payments || []) : [];
    const matchedStoreDocs = storePayments.filter((inv: any) => isInvoiceMatchingMember(inv, memberInfo));
    matchedStoreDocs.forEach((inv: any) => {
      const key = inv.id || inv.invoiceNumber || inv.invoice || `store_${Math.random()}`;
      combinedMap.set(key, inv);
    });

    // 1. Live Firestore matches
    matchedDocs.forEach((inv: any) => {
      const key = inv.id || inv.invoiceNumber || inv.invoice || `live_${Math.random()}`;
      combinedMap.set(key, inv);
    });

    // 2. Embedded history matches
    embeddedRaw.forEach((inv: any, idx: number) => {
      const key = inv?.id || inv?.invoiceNumber || inv?.invoice || `emb_${idx}`;
      if (!combinedMap.has(key)) {
        combinedMap.set(key, inv);
      }
    });

    // 3. Check if combinedMap has valid payment records with price > 0
    const hasValidPayment = Array.from(combinedMap.values()).some((inv: any) => {
      if (!inv || inv.deleted === true || String(inv.status || '').toLowerCase() === 'void') return false;
      const price = Number(inv.netPayable || inv.amount || inv.originalAmount || inv.price || extractPriceFromPlanString(inv.plan) || 0);
      return price > 0;
    });

    // 4. Auto-generated fallback invoice if member has package/due info but no valid payment records
    if (!hasValidPayment && member) {
      const rawPaid = member.amountPaid ?? member.paid ?? member.totalPaid ?? member.paidAmount ?? member.amount ?? 0;
      const rawBalance = member.balanceAmount ?? member.balance ?? member.outstandingBalance ?? member.balanceDue ?? member.dueAmount ?? member.pendingAmount ?? 0;
      const rawPrice = member.price ?? member.packagePrice ?? member.planPrice ?? member.planAmount ?? member.totalBilled ?? member.amount ?? 0;

      let extractedPrice = Number(rawPrice) || getDefaultPriceForPlan(member.plan || member.packageName);

      let balanceAmount = Number(rawBalance) || 0;
      let amountPaid = Number(rawPaid) || 0;

      const isPaidOrActive = (member.paymentStatus || '').toLowerCase() === 'paid' ||
                            (member.status || '').toLowerCase() === 'active' ||
                            balanceAmount === 0;

      if (amountPaid === 0 && (isPaidOrActive || balanceAmount > 0)) {
        if (balanceAmount > 0 && extractedPrice > balanceAmount) {
          amountPaid = extractedPrice - balanceAmount;
        } else if (balanceAmount === 0) {
          amountPaid = extractedPrice || 2000;
        }
      }

      const totalBilled = Number(member.totalBilled) || (amountPaid + balanceAmount) || extractedPrice || 2000;
      const planPrice = totalBilled || extractedPrice || 2000;

      const payStatus = balanceAmount === 0 ? 'paid' : (amountPaid > 0 ? 'partial' : 'pending');
      const membershipLabel = member.packageName || (typeof member.plan === 'string' ? member.plan.split('₹')[0].trim() : 'General Membership') || 'General Membership';
      const invNum = member.memberId ? `INV-${String(member.memberId).replace('AZ-2026-', '').replace('AZ-', '')}` : (member.clientId ? `INV-LEG-${member.clientId}` : `INV-AUTO-${member.id || '670'}`);

      const autoInv = {
        id: `inv_auto_${member.id || member.uid || Date.now()}`,
        invoiceNumber: invNum,
        invoice: invNum,
        plan: membershipLabel,
        packageName: membershipLabel,
        amount: (payStatus === 'paid' && amountPaid > 0) ? amountPaid : planPrice,
        totalBilled: planPrice,
        packagePrice: planPrice,
        originalAmount: planPrice,
        netPayable: (payStatus === 'paid' && amountPaid > 0) ? amountPaid : planPrice,
        amountPaid: amountPaid,
        paid: amountPaid,
        pendingAmount: balanceAmount,
        balanceAmount: balanceAmount,
        paymentMethod: member.paymentMethod || member.method || 'Cash',
        status: payStatus,
        billingType: 'membership',
        date: member.startDate || member.joinDate || new Date().toISOString().split('T')[0],
        createdAt: member.createdAt || member.joinDate || new Date().toISOString(),
        memberId: member.id || member.memberId || member.uid,
        memberName: member.name || 'Member',
        memberPhone: member.phone || '',
        isAutoGenerated: true
      };

      combinedMap.set(autoInv.id, autoInv);
    }

    // 5. Normalize all records
    const normalized = Array.from(combinedMap.values()).map(raw => normalizeBillingTransaction(raw, member));

    // Sort descending by date
    normalized.sort((a, b) => {
      const dtA = new Date(a.billDate || a.createdAt).getTime();
      const dtB = new Date(b.billDate || b.createdAt).getTime();
      return (isNaN(dtB) ? 0 : dtB) - (isNaN(dtA) ? 0 : dtA);
    });

    const summary = calculateBillingSummary(normalized);

    const diagnostics: BillingDiagnostics = {
      memberDocId: String(member.id || member.docId || ''),
      canonicalMemberId: String(member.memberId || member.clientId || member.id || ''),
      allMemberKeys: Array.from(memberInfo.keysSet),
      phoneMatched: memberInfo.phone,
      nameMatched: memberInfo.name,
      firestoreLiveCount: matchedDocs.length,
      embeddedCount: embeddedRaw.length,
      normalizedCount: normalized.length,
      billed: summary.totalBilled,
      collected: summary.totalCollected,
      pending: summary.totalPending
    };

    return { normalized, summary, diagnostics };
  };

  const unsub = onSnapshot(collection(db, 'payments'), (snap) => {
    const allDocs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    const matchedDocs = allDocs.filter(inv => isInvoiceMatchingMember(inv, memberInfo));
    const { normalized, summary, diagnostics } = buildNormalizedList(matchedDocs);
    onUpdate(normalized, summary, diagnostics);
  }, (err) => {
    console.warn('[billingService] Firestore listener notice:', err);
    const { normalized, summary, diagnostics } = buildNormalizedList([]);
    onUpdate(normalized, summary, diagnostics);
  });

  return unsub;
}
