import { db } from '@/lib/firebase';
import { collection, query, where, getDocs, onSnapshot, Unsubscribe } from 'firebase/firestore';

export interface NormalizedBillingTransaction {
  id: string;
  invoiceNumber: string;
  invoice: string;
  memberId: string;
  clientId?: string;
  memberName: string;
  memberPhone?: string;
  billingType: 'membership' | 'pt' | 'other';
  transactionType?: string;
  plan: string;
  packageName: string;
  date: string;
  billDate: string;
  startDate: string;
  expiryDate: string;
  amount: number;
  originalAmount: number;
  discount: number;
  discountAmount: number;
  tax: number;
  taxAmount: number;
  otherCharges: number;
  netPayable: number;
  paid: number;
  amountPaid: number;
  pendingAmount: number;
  balanceAmount: number;
  method: string;
  paymentMethod: string;
  status: 'paid' | 'partial' | 'pending' | 'void';
  isHistorical?: boolean;
  isAutoGenerated?: boolean;
  createdAt: string;
  raw: any;
}

export interface BillingSummary {
  totalBilled: number;
  totalCollected: number;
  totalPending: number;
}

export interface BillingDiagnostics {
  memberDocId: string;
  canonicalMemberId: string;
  allMemberKeys: string[];
  phoneMatched: string;
  firestoreLiveCount: number;
  embeddedCount: number;
  normalizedCount: number;
  billed: number;
  collected: number;
  pending: number;
}

/**
 * 1. RESOLVE ALL STABLE MEMBER IDENTIFIER KEYS
 * Given any member object or string, extracts all variations:
 * - docId / id / uid
 * - memberId (e.g. AZ-2026-0028)
 * - clientId (e.g. 28)
 * - member_28, member_AZ-2026-0028
 * - numeric suffix (28)
 */
export function resolveMemberIdentifierKeys(member: any): { keysSet: Set<string>; cleanNumsSet: Set<string>; phone: string } {
  if (!member) return { keysSet: new Set(), cleanNumsSet: new Set(), phone: '' };

  const rawKeys: string[] = [];
  if (typeof member === 'string') {
    rawKeys.push(member);
  } else if (typeof member === 'object') {
    if (member.id) rawKeys.push(String(member.id));
    if (member.docId) rawKeys.push(String(member.docId));
    if (member.uid) rawKeys.push(String(member.uid));
    if (member.memberId) rawKeys.push(String(member.memberId));
    if (member.clientId) rawKeys.push(String(member.clientId));
    if (member.memberCode) rawKeys.push(String(member.memberCode));
    if (member.employeeId) rawKeys.push(String(member.employeeId));

    // Add prefixed variations used by migration imports (member_${clientId})
    if (member.clientId) {
      rawKeys.push(`member_${member.clientId}`);
      rawKeys.push(`member_AZ-${member.clientId}`);
      rawKeys.push(`member_AZ-2026-${member.clientId}`);
    }
    if (member.memberId) {
      rawKeys.push(`member_${member.memberId}`);
    }
  }

  const keysSet = new Set<string>();
  const cleanNumsSet = new Set<string>();

  rawKeys.forEach(k => {
    if (!k) return;
    const lower = k.trim().toLowerCase();
    keysSet.add(lower);

    // Extract numeric portion (e.g. "AZ-2026-0028" -> "28" or "0028")
    const cleanNum = lower.replace(/^(member_|az-2026-|az-)/i, '').replace(/^0+/, '');
    if (cleanNum) cleanNumsSet.add(cleanNum);
  });

  const rawPhone = typeof member === 'object' ? (member.phone || member.mobile || member.memberPhone || '') : '';
  const phone = String(rawPhone).replace(/\D/g, '');

  return { keysSet, cleanNumsSet, phone };
}

/**
 * 2. MATCH AN INVOICE RECORD AGAINST MEMBER IDENTIFIERS
 */
export function isInvoiceMatchingMember(inv: any, memberInfo: { keysSet: Set<string>; cleanNumsSet: Set<string>; phone: string }): boolean {
  if (!inv || inv.deleted === true || String(inv.status || '').toLowerCase() === 'void' || inv.isDuplicate === true) {
    return false;
  }

  const { keysSet, cleanNumsSet, phone } = memberInfo;

  const invKeys = [
    inv.memberId,
    inv.clientId,
    inv.uid,
    inv.docId,
    inv.memberCode,
    inv.employeeId,
    inv.userId,
    inv.id
  ].filter(Boolean).map(x => String(x).trim().toLowerCase());

  // Direct match on any key
  for (const ik of invKeys) {
    if (keysSet.has(ik)) return true;

    const invCleanNum = ik.replace(/^(member_|az-2026-|az-)/i, '').replace(/^0+/, '');
    if (invCleanNum && cleanNumsSet.has(invCleanNum)) return true;
  }

  // Phone match as secondary fallback
  if (phone && phone.length >= 7) {
    const invPhone = String(inv.memberPhone || inv.phone || inv.mobile || '').replace(/\D/g, '');
    if (invPhone && (invPhone === phone || invPhone.endsWith(phone) || phone.endsWith(invPhone))) {
      return true;
    }
  }

  return false;
}

/**
 * 3. NORMALIZE A RAW BILLING TRANSACTION RECORD
 */
export function normalizeBillingTransaction(rawRecord: any, defaultMember?: any): NormalizedBillingTransaction {
  const r = rawRecord || {};

  const origAmt = Number(r.originalAmount !== undefined ? r.originalAmount : (r.packagePrice || r.price || r.amount || r.totalBilled || 0));
  const discAmt = Number(r.discountAmount !== undefined ? r.discountAmount : (r.discount || 0));
  const taxAmt = Number(r.taxAmount !== undefined ? r.taxAmount : (r.tax || r.gst || 0));
  const othAmt = Number(r.otherCharges || 0);

  const calcNet = Math.max(0, origAmt - discAmt + taxAmt + othAmt);
  const netPayable = Number(r.netPayable !== undefined ? r.netPayable : (r.amount !== undefined ? r.amount : calcNet));
  const amountPaid = Number(r.amountPaid !== undefined ? r.amountPaid : (r.paid !== undefined ? r.paid : (r.amountPaidToday !== undefined ? r.amountPaidToday : netPayable)));

  const rawPending = r.pendingAmount !== undefined ? r.pendingAmount : (r.balanceAmount !== undefined ? r.balanceAmount : (r.outstandingAmount !== undefined ? r.outstandingAmount : (r.remainingBalance !== undefined ? r.remainingBalance : (netPayable - amountPaid))));
  const pendingAmount = Math.max(0, Number(rawPending) || 0);

  let status: 'paid' | 'partial' | 'pending' | 'void' = 'paid';
  const rawStatus = String(r.status || r.paymentStatus || '').toLowerCase();
  if (rawStatus === 'void' || r.deleted === true) {
    status = 'void';
  } else if (pendingAmount === 0 || rawStatus === 'paid') {
    status = 'paid';
  } else if (amountPaid > 0 || rawStatus === 'partial') {
    status = 'partial';
  } else {
    status = 'pending';
  }

  const invNum = r.invoiceNumber || r.invoice || r.invoiceNo || (r.clientId ? `INV-LEG-${r.clientId}` : (r.id ? `INV-${r.id}` : 'INV-001'));
  const bType = String(r.billingType || r.invoiceType || r.type || '').toLowerCase().includes('pt') ? 'pt' : 'membership';

  const planName = r.plan || r.packageName || r.package || defaultMember?.plan || defaultMember?.packageName || 'General Membership';
  const dateStr = r.billDate || r.date || r.paymentDate || r.startDate || r.createdAt || new Date().toISOString().split('T')[0];

  return {
    id: String(r.id || invNum),
    invoiceNumber: String(invNum),
    invoice: String(invNum),
    memberId: String(r.memberId || defaultMember?.id || defaultMember?.memberId || ''),
    clientId: r.clientId ? String(r.clientId) : undefined,
    memberName: String(r.memberName || defaultMember?.name || 'Gym Member'),
    memberPhone: String(r.memberPhone || r.phone || defaultMember?.phone || ''),
    billingType: bType,
    transactionType: r.transactionType || r.type || 'membership_payment',
    plan: String(planName),
    packageName: String(planName),
    date: String(dateStr),
    billDate: String(dateStr),
    startDate: String(r.startDate || dateStr),
    expiryDate: String(r.expiryDate || r.endDate || ''),
    amount: netPayable,
    originalAmount: origAmt,
    discount: discAmt,
    discountAmount: discAmt,
    tax: taxAmt,
    taxAmount: taxAmt,
    otherCharges: othAmt,
    netPayable,
    paid: amountPaid,
    amountPaid,
    pendingAmount,
    balanceAmount: pendingAmount,
    method: String(r.paymentMethod || r.method || 'Cash'),
    paymentMethod: String(r.paymentMethod || r.method || 'Cash'),
    status,
    isHistorical: Boolean(r.isHistorical || r.imported || r.isLegacyImport),
    isAutoGenerated: Boolean(r.isAutoGenerated),
    createdAt: String(r.createdAt || dateStr),
    raw: r
  };
}

/**
 * 4. CALCULATE CANONICAL FINANCIAL SUMMARY
 */
export function calculateBillingSummary(transactions: NormalizedBillingTransaction[]): BillingSummary {
  const active = transactions.filter(t => t.status !== 'void');

  const totalBilled = active.reduce((sum, t) => {
    const isUp = t.transactionType === 'membership_upgrade' || String(t.invoiceNumber || '').startsWith('INV-UPG');
    if (isUp) {
      return sum + t.netPayable;
    }
    return sum + (t.netPayable || t.originalAmount);
  }, 0);

  const totalCollected = active.reduce((sum, t) => sum + t.amountPaid, 0);
  const totalPending = Math.max(0, totalBilled - totalCollected);

  return { totalBilled, totalCollected, totalPending };
}

/**
 * 5. GET MEMBER BILLING TRANSACTIONS (REALTIME LISTENER WITH EMBEDDED FALLBACKS)
 */
export function listenMemberBillingTransactions(
  member: any,
  onUpdate: (transactions: NormalizedBillingTransaction[], summary: BillingSummary, diagnostics: BillingDiagnostics) => void
): Unsubscribe {
  if (!member) {
    onUpdate([], { totalBilled: 0, totalCollected: 0, totalPending: 0 }, {
      memberDocId: '',
      canonicalMemberId: '',
      allMemberKeys: [],
      phoneMatched: '',
      firestoreLiveCount: 0,
      embeddedCount: 0,
      normalizedCount: 0,
      billed: 0,
      collected: 0,
      pending: 0
    });
    return () => {};
  }

  const memberInfo = resolveMemberIdentifierKeys(member);

  // Embedded records on member document
  const embeddedRaw: any[] = [
    ...(Array.isArray(member.billingHistory) ? member.billingHistory : []),
    ...(Array.isArray(member.payments) ? member.payments : []),
    ...(Array.isArray(member.membershipHistory) ? member.membershipHistory : []),
    ...(Array.isArray(member.ptHistory) ? member.ptHistory : [])
  ];

  const unsub = onSnapshot(collection(db, 'payments'), (snap) => {
    const allDocs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    const matchedDocs = allDocs.filter(inv => isInvoiceMatchingMember(inv, memberInfo));

    const combinedMap = new Map<string, any>();

    // 1. Live Firestore matches
    matchedDocs.forEach((inv: any) => {
      const key = inv.id || inv.invoiceNumber || inv.invoice || `live_${Math.random()}`;
      combinedMap.set(key, inv);
    });

    // 2. Embedded history matches
    embeddedRaw.forEach((inv: any, idx: number) => {
      const key = inv?.id || inv?.invoiceNumber || inv?.invoice || `emb_${idx}`;
      if (!combinedMap.has(key)) {
        combinedMap.set(key, inv);
      }
    });

    // 3. Auto-generated fallback invoice if member has package/due info but no payment records
    if (combinedMap.size === 0 && member) {
      const rawPaid = member.amountPaid ?? member.paid ?? member.totalPaid ?? member.paidAmount ?? member.amount ?? 0;
      const rawBalance = member.balanceAmount ?? member.balance ?? member.outstandingBalance ?? member.balanceDue ?? member.dueAmount ?? member.pendingAmount ?? 0;
      const rawPrice = member.price ?? member.packagePrice ?? member.planPrice ?? member.planAmount ?? member.totalBilled ?? member.amount ?? 0;

      let extractedPrice = Number(rawPrice) || 0;
      if (!extractedPrice && typeof member.plan === 'string') {
        const match = member.plan.match(/₹?\s*([0-9,]+)/);
        if (match) extractedPrice = Number(match[1].replace(/,/g, ''));
      }
      if (!extractedPrice && typeof member.packageName === 'string') {
        const match = member.packageName.match(/₹?\s*([0-9,]+)/);
        if (match) extractedPrice = Number(match[1].replace(/,/g, ''));
      }
      if (!extractedPrice && (member.plan || member.packageName)) {
        extractedPrice = 5000;
      }

      let balanceAmount = Number(rawBalance) || 0;
      let amountPaid = Number(rawPaid) || 0;

      const isPaidOrActive = (member.paymentStatus || '').toLowerCase() === 'paid' ||
                            (member.status || '').toLowerCase() === 'active' ||
                            balanceAmount === 0;

      if (amountPaid === 0 && (isPaidOrActive || balanceAmount > 0)) {
        if (balanceAmount > 0 && extractedPrice > balanceAmount) {
          amountPaid = extractedPrice - balanceAmount;
        } else if (balanceAmount === 0) {
          amountPaid = extractedPrice || 5000;
        }
      }

      const totalBilled = Number(member.totalBilled) || (amountPaid + balanceAmount) || extractedPrice || 5000;
      const planPrice = totalBilled || extractedPrice || 5000;

      const payStatus = balanceAmount === 0 ? 'paid' : (amountPaid > 0 ? 'partial' : 'pending');
      const membershipLabel = member.packageName || (typeof member.plan === 'string' ? member.plan.split('₹')[0].trim() : 'General Membership') || 'General Membership';
      const invNum = member.memberId ? `INV-${String(member.memberId).replace('AZ-2026-', '').replace('AZ-', '')}` : (member.clientId ? `INV-LEG-${member.clientId}` : `INV-AUTO-${member.id || '670'}`);

      const autoInv = {
        id: `inv_auto_${member.id || member.uid || Date.now()}`,
        invoiceNumber: invNum,
        invoice: invNum,
        plan: membershipLabel,
        packageName: membershipLabel,
        amount: planPrice,
        totalBilled: planPrice,
        packagePrice: planPrice,
        originalAmount: planPrice,
        netPayable: planPrice,
        amountPaid: amountPaid,
        paid: amountPaid,
        pendingAmount: balanceAmount,
        balanceAmount: balanceAmount,
        paymentMethod: member.paymentMethod || member.method || 'Cash',
        status: payStatus,
        billingType: 'membership',
        date: member.startDate || member.joinDate || new Date().toISOString().split('T')[0],
        createdAt: member.createdAt || member.joinDate || new Date().toISOString(),
        memberId: member.id || member.memberId || member.uid,
        memberName: member.name || 'Member',
        memberPhone: member.phone || '',
        isAutoGenerated: true
      };

      combinedMap.set(autoInv.id, autoInv);
    }

    // 4. Normalize all records
    const normalized = Array.from(combinedMap.values()).map(raw => normalizeBillingTransaction(raw, member));

    // Sort descending by date
    normalized.sort((a, b) => {
      const dtA = new Date(a.billDate || a.createdAt).getTime();
      const dtB = new Date(b.billDate || b.createdAt).getTime();
      return (isNaN(dtB) ? 0 : dtB) - (isNaN(dtA) ? 0 : dtA);
    });

    const summary = calculateBillingSummary(normalized);

    const diagnostics: BillingDiagnostics = {
      memberDocId: String(member.id || member.docId || ''),
      canonicalMemberId: String(member.memberId || member.clientId || member.id || ''),
      allMemberKeys: Array.from(memberInfo.keysSet),
      phoneMatched: memberInfo.phone,
      firestoreLiveCount: matchedDocs.length,
      embeddedCount: embeddedRaw.length,
      normalizedCount: normalized.length,
      billed: summary.totalBilled,
      collected: summary.totalCollected,
      pending: summary.totalPending
    };

    onUpdate(normalized, summary, diagnostics);
  }, (err) => {
    console.warn('[billingService] Firestore listener notice:', err);
    const normalizedEmbedded = embeddedRaw.map(raw => normalizeBillingTransaction(raw, member));
    const summary = calculateBillingSummary(normalizedEmbedded);

    const diagnostics: BillingDiagnostics = {
      memberDocId: String(member.id || member.docId || ''),
      canonicalMemberId: String(member.memberId || member.clientId || member.id || ''),
      allMemberKeys: Array.from(memberInfo.keysSet),
      phoneMatched: memberInfo.phone,
      firestoreLiveCount: 0,
      embeddedCount: embeddedRaw.length,
      normalizedCount: normalizedEmbedded.length,
      billed: summary.totalBilled,
      collected: summary.totalCollected,
      pending: summary.totalPending
    };

    onUpdate(normalizedEmbedded, summary, diagnostics);
  });

  return unsub;
}
